### ISSUE TITLE
Conda availability?

### ISSUE THREAD

**Issue by AntonioBaeza** [art-egorov/lovis4u#1]
Any chance you can make it available via Conda? Thanks!

**Comment by art-egorov** [comment]
Hi! You can simply use `python3 -m pip install lovis4u` with activated conda environment and it will install the tool in it. Since it is purely python library wo required installation of non-python dependencies (there is mmseqs2, but it's embedded within the library and hidden) that will be the same and there will be no needs for additional settings. 
If something goes wrong in that case with installation or smth else - let us know, I'll try to help.

Best

**Comment by AntonioBaeza** [comment]
thank you, I will try it! Best, Antonio

**Comment by gbouras13** [comment]
@art-egorov awesome piece of software mate! Will be a staple for my group now. 

Just weighing in here, regardless of it being pure python, I'd still recommend you put it on Bioconda for maximal user friendliness and reach - if you haven't done it before, there's recently been an awesome guide posted on how to do it, should be apiece of cake as you have a pypi install already.

https://ubinfie.github.io/2024/08/16/adding-to-bioconda-quickguide.html
https://ubinfie.github.io/2024/08/16/updating-bioconda-recipe-quickguide

George

**Comment by art-egorov** [comment]
@gbouras13 
Thank you, George!
I agree, though I’m not a big fan of conda for pure python packages suitable for pypi... But yep, some people could prefer such way, I’ll add putting it there to the to-do list :)  

Besy,
Artyom
