### ISSUE TITLE
Disable clustering if input is a single genome

### ISSUE THREAD

**Issue by apcamargo** [art-egorov/lovis4u#13]
If the input is a single sequence, there's no need to cluster proteins and the MMseqs2 execution can be skipped.

**Comment by art-egorov** [comment]
I think keeping it by default is better than not, but I see currently a problem that clustering doesn't affect visualisation (does not colour different families by colour to highlight duplication events or smth like that by default, even though can be easily activated as shown in the Gallery). I will adjust it within few days. 
If you need to deactivate clustering you can always simply use `--mmseqs-off` cmd parameter (or by skipping run of `loci.mmseqs_cluster()` function in API.

Best

**Comment by apcamargo** [comment]
My bad. I completely missed this option!

**Comment by apcamargo** [comment]
Not sure if this is what you were referring to, but when I use `--mmseqs-off` the resulting figures don't have labels in the features.

**Comment by art-egorov** [comment]
Yep, that's why I said default behaviour should be adjusted for single genome case :)
Since by default labels are shown only for "accessory" features or features that had hits with pyhmmer search, by default with single sequence it looks funky.
You can show all features by using `-safl`or  `--show-all-feature-labels`  parameter 

Best
