### ISSUE TITLE
Some minor enhancement suggestions

### ISSUE THREAD

**Issue by Dx-wmc** [art-egorov/lovis4u#2]
Hi, It's great to find such a great tool on biorxiv, and as far as I use it, I find it very handy. Since I mainly do genome comparisons, I have some small enhancements for comparisons here: 

1. mmseq works great, but is it possible to introduce some other comparison tools? For example, mumer or blast, the reason is that in the process of plotting my own data, there is more spacing from gene to gene, mmseq then only provides comparison between proteins, so the view will be inferior to blast's plotting.

<img width="1013" alt="image" src="https://github.com/user-attachments/assets/0bb48a93-02b5-4c9f-b492-2887a69b24b3">

2. Can homology-links increase the way they are presented, such as curves like this?
![image](https://github.com/user-attachments/assets/88219eff-5a75-4f33-b1e3-ac9a6517bc89)

**Comment by art-egorov** [comment]
Hi! Thank you very much for comments and sharing ideas!
1. I’m planning to add non-coding gene features for visualisation, along with nucleotide-level comparisons of them. However, at this moment we don't plan to add just full length nucleotide sequence alignments since it is rarely will be useful for microbial genomes with small intergenic regions. If you mean comparison of eukaryotic genomes, then LoVis4u would be quite bad solution at least for now. For instance, we cannot hide or even just plot introns and not sure if I will be able to build a solution for that in the near future. But maybe later...
2. I think it is possible but here also the issue with microbial genomes is that the intergenic regions are small, which could make things a bit confusing. I'll add this idea to the to-do list and will have a look what can be done when I will be updating homology lines. 

Best,
Artyom

**Comment by Dx-wmc** [comment]
The graph above may have some misunderstandings, and I also work on prokaryotic microorganisms. Looking forward to seeing better software updates.
