### ISSUE TITLE
lovis4u: command not found (conda installation issue)

### ISSUE THREAD

**Issue by CorentinEscobar** [art-egorov/lovis4u#9]
Hello,

I installed lovis4u in a conda environment, with the command python3 -m pip install lovis4u as indicated. However, when I run the command lovis4u --linux then I have the error "command not found"

Thanks for your help

Corentin

**Comment by art-egorov** [comment]
Hi! Thank you for trying lovis4u and this report.
Yep, I tested on an empty conda env and got the same error. 
Seems in general it can be fixed by the following way:
You first install (verify that installed) conda 'pip' library with : `conda install pip` and then install lovis4u directly with it wo specifying python version: `pip install lovis4u` which makes then "bin" file available within conda env. At least it worked in my case.. 
Let me know, please, if it doesn't solve your problem
As i replied in another issue comment, I have plans to add lovis4u to conda as well to avoid such problems in the next releases

Best,
Artyom

**Comment by CorentinEscobar** [comment]
It's perfect, it works!
Thank you very much !

Best,
Corentin

**Comment by art-egorov** [comment]
I'm glad it helped, thank you too! :) 

Best,
Artyom

**Comment by apcamargo** [comment]
@art-egorov Out of curiosity, is there a reason LoVis4u is not available as an actual Conda package? I was considering creating a recipe for it, but wanted to check with you first.

**Comment by art-egorov** [comment]
@apcamargo
Hi Antônio!
The only reason that I personally don't really conda envs :). It's still in the to do list to build a recipe and deploy there..  
Seems there are some recipe building tools based on pypi packages for super fast deployment though. I'll have a look this week

**Comment by apcamargo** [comment]
No worries! I was just curious.

I was looking at the dependencies myself and noticed that there's a `argparse` dependency. Is there any reason for that, since it is included in the standard Python distribution?

**Comment by art-egorov** [comment]
Thank you for noticing! Nope, there is no good reason, just accidentally left there from old times. I'll publish a rare bug fixing update for features wo specified orientation today with this part removed.
